version: 0.2
env:
  variables:
    S3_BUCKET: "hackernews"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - aws s3 cp dist/Yhacker s3://${S3_BUCKET}
      - aws s3 cp dist/Yhacker/assets s3://${S3_BUCKET}/assets
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist/Yhacker*'
  discard-paths: yes
  
  